### ISSUE TITLE
proxy approach does not seem to work for xml files

### ISSUE THREAD

**Issue by ssvw** [jakerella/jquery-mockjax#105]
It seems like xml files do not work for the proxy approach. Tested with both json and xml proxy files and the latter would'nt work. Could you please fix that? Used

```html
<script src="../lib/jquery-1.10.2.min.js"></script>
<script src="../lib/jquery-migrate-1.2.1.min.js"></script>
<script src="../lib/jquery.mockjax.js"></script>
```

as libraries. responseXML worked like a charm. However, for more complex xml files, the proxy approach would be of great help.

**Comment by jakerella** [comment]
This should be resolved (according to our tests) in `master`. I'll try to cut a release for this and other fixes soon.
