### ISSUE TITLE
mockjax fatal flow

### ISSUE THREAD

**Issue by valtido** [jakerella/jquery-mockjax#120]
Hi Guys,

Sorry if I sound sooo stupid, or if it's just funcunit, that is being stupid.

I feel the flow should be like this...

test.js
```
$.mockjax({
   url: '*',
   responseText: {"hello":"world"},
   use: 'success,complete,always',//*** check below
   success: function (res){
        equal(res.hello,"world");
        equal($('body').text(),"world");
   }
});
```

code.js // actual real code
```
//ajax should be intercepted, grab the success, handler and trigger it
// using the $.ajaxSetup( {beforeSend: function (){ ...trigger success with above responseText...  }} );
//as an interceptor
//*** 
$.ajax({
    url: '[...]', //what ever it may be
    success : function (res){
       $('body').text(res.hello)
    }
});

```

The reason for the above, is because we want to seperate the test from the real ajax, and also we do not want to maintain two $.ajax everytime one changes or the other....

this way, you will only need to change the handlers not the whole ajax...

(I could be wrong.... but what do you guys think about this?)

**Comment by jakerella** [comment]
Closing due to lack of response. Feel free to reopen if we get more info!
