### ISSUE TITLE
Mockjax intercepts crossDomain script requests, but then fails to handle them.

### ISSUE THREAD

**Issue by dcneiner** [jakerella/jquery-mockjax#136]
To reproduce: 

```js
$.mockjax({
    url: "http://sample.com/somefile.js",
    responseText: "alert('hi');"
});

$.ajax({
    type: "GET",
    dataType: "script",
    url: "http://sample.com/somefile.js"
});
```

**Expected behavior:** An alert with `hi`
**Actual behavior:** Request is made for `"http://sample.com/somefile.js"`

At least in hacking with this, one fix was to put `origSettings.crossDomain = false;` on line 471.

**Comment by szalishchuk** [comment]
This hack works only for GET type, with POST request is not intercepted.

**Comment by r4j4h** [comment]
Just wanting to note for other users that this problem still persists.

**Comment by jakerella** [comment]
Yep... haven't had time to tinker with it... :(

Suggestions on fixes that solve for all methods??

**Comment by r4j4h** [comment]
Well after some further debugging with the original code we had a simulated timeout keeping our function from being executed (using jasmine mocked clock). So in other words this is not a still persisting problem, at least for our use case of a GET with cross domain, and we do not need the hack.

**Comment by jakerella** [comment]
@r4j4h That's good to hear! Of course, I think the issue still exists, based on our simple test, but at least your tests work!

**Comment by jakerella** [comment]
I've added two tests for cross domain requests (`GET` and `POST`) and implemented @dcneiner's hack. I think it's a safe hack, and I don't see many other (easy) options. Hopefully this resolves the issue, please ping me here if not.
