### ISSUE TITLE
POST-request with `contentType: application/json` is not working correctly.

### ISSUE THREAD

**Issue by RubaXa** [jakerella/jquery-mockjax#141]
Example ([http://jsfiddle.net/34bZp/2/](jsfiddle.net/34bZp/2)):
```js
// Set POST-mock
$.mockjax({
    url: '/bar',
    type: 'POST',
    contentType: 'application/json',
    responseText: JSON.stringify({ res: "bar" })
});

// Send POST-request with any data
$.ajax({
    url: '/bar',
    type: 'POST',
    data: { any: "data" }  // without `data` working correctly
}).always(function (json) {
    console.log(json); // Oops, this is a string `res: "bar"`
});
```

This occurs because:
 1. https://github.com/jquery/jquery/blob/master/src/ajax.js#L549-L550
 2. https://github.com/jquery/jquery/blob/master/src/ajax.js#L22
 3. https://github.com/jquery/jquery/blob/master/src/ajax.js#L588-L591

**Comment by jakerella** [comment]
Looks like this was fixed somewhere along the way (without really attempting to :smile_cat:). See this [updated fiddle](http://jsfiddle.net/34bZp/3/) using 1.6.2. Closing for now, but feel free reopen if need be.
