### ISSUE TITLE
Allow for multiple mock handler setup in single call

### ISSUE THREAD

**Issue by jakerella** [jakerella/jquery-mockjax#188]
This would really just be more of a convenience for people who wanted to set up a few mocks in a single call. Any thoughts?

```javascript
// example of what it might look like...
$.mockjax([  // note an array vs object or function
    { url: "/api/user/id", ..., responseText: "13" },
    { url: "/api/user/name", ..., responseText: "Jordan" },
    ...
]);
```

**Comment by koorgoo** [comment]
@jakerella how soon will version 2.2 be released? The milestone is reached.

**Comment by jakerella** [comment]
Doing some testing on various browsers. See PR #294

**Comment by koorgoo** [comment]
Thank you, looking forward to it!
