### ISSUE TITLE
$.ajax .type vs .method

### ISSUE THREAD

**Issue by jakecraige** [jakerella/jquery-mockjax#190]
The jquery-mockjax codebase references `requestSettings.type` throughout. This lib has some weird behavior in a few places because of it and it should just polyfil it.

The jQuery commit is [here](https://github.com/jquery/jquery/commit/081c4efcf7736433d2fb5702e7bd4f8616426af2)

working on PR now

**Comment by jakerella** [comment]
This was resolved in #196.
