### ISSUE TITLE
Immediate Return Option

### ISSUE THREAD

**Issue by machineghost** [jakerella/jquery-mockjax#201]
In a test environment any kind of delay can be  inconvenient, because it means interrupting the normal test runner flow.  That in turn means that any related logic which fails will fail outside the test's scope, leaving the test runner unable to properly report those failures.  However, even if one uses mockjax it is difficult to avoid this, because mockjax (almost) always runs asynchronously, even with a timeout of 0.

This problem has a simple solution: make mocked AJAX requests return immediately (ie. synchronously).  However, the only way to do that in mockjax right now is to specify "async: false" ... in the _production_ code.  When a developer only wants to run synchronously in a test environment, having to change production code somewhat defeats the purpose of using a mock.

It would be very handy if there was a way to tell mockjax "pretend this AJAX request returned immediately, so I don't have to interrupt my test flow", and there easily could be with only two small changes to mockjax's code ...

```
if ( requestSettings.async === false) {
    // TODO: Blocking delay
    process();
} else {
    this.responseTimer = setTimeout(process, parseResponseTimeOpt(mockHandler.responseTime) || 50);
}
```

to:

```
if ( requestSettings.async === false || mockHandler.async === false) {
    // TODO: Blocking delay
    process();
} else {
    this.responseTimer = setTimeout(process, parseResponseTimeOpt(mockHandler.responseTime) || 50);
}
```

and:

```
(function(mockHandler, requestSettings, origSettings, origHandler) {
    mockRequest = _ajax.call($, $.extend(true, {}, origSettings, {
```

to:

```
(function(mockHandler, requestSettings, origSettings, origHandler) {
    if (mockHandler.async === false) {
        origSettings.async = false;
    }
    mockRequest = _ajax.call($, $.extend(true, {}, origSettings, {
```

I hope you will consider this idea, as I think it would be a great improvement to an already great tool.

**Comment by juanmendes** [comment]
Voting for `async: false` setting. A synchronous test is much simpler to maintain and I don't need setup and teardowns

**Comment by jakerella** [comment]
@juanmendes Thanks for the vote, and for participating in the conversation, but the opinion of the core contributors is that this would not be a wise addition. Making mock ajax calls no longer asynchronous when they were specified as such in the source code could easily cause false positive (or negative) test results.

We will not be implementing this feature, but you can always do it in a fork if you feel it is necessary.

**Comment by juanmendes** [comment]
I did read the conversation and only posted because it was said that if there was enough support from the community, you may consider it. 

I have been using synchronous mocking of AJAX calls for a long time (and also have written more lines of JavaScript test code than most have written lines of JavaScript :smiley: ) and have never encountered a false positive or negative because of making the calls synchronous in tests. Have you actually had problems or are you simply being extra cautious?

**Comment by jakerella** [comment]
Yes, I have had this bite me before. When you switch a function's execution from being async to sync things can happen out of expected order in your source code. This can cause (or remove) race conditions that do/don't actually exist in the source. In other words, those can be missed by the tests.

This is not just my opinion, it is that of the other contributors and a few other devs I've asked. Our thought is that this is a bad practice. It fundamentally changes the way the XMLHttpRequest was created, not just mocking, but changing the execution path and strategy of the JS engine.

**Comment by machineghost** [comment]
@juanmendes the maintainers of this library have made it clear that they don't care about community feedback on this issue. They've also made it clear that they won't improve things for JS  professionals with real-world use cases *so long as* there is any chance that some moron developer who doesn't understand what asynchronicity means might shoot themselves in the foot by using a feature they don't understand.

****shrug**** It's their library and their call.  My advice is to just use Sinon as much as possible to eliminate the need for mockJax in unit tests, and then use Selenium when you actually need to test real world timing stuff.

**Comment by juanmendes** [comment]
@machineghost I think they do care. I think they are just being a bit overzealous. I'm just hoping maybe others will ask for the same feature too. Your flaming response won't help our cause though :smile:

**Comment by jakerella** [comment]
@juanmendes Thanks for the vote of confidence. Seeing as how some folks can't keep things polite I'll have to lock this issue.
