### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by s-panferov** [jakerella/jquery-mockjax#204]
It will be nice to have `.d.ts` definition file for `jquery-mockjax` on http://www.tsdpm.com/. Do you have any plans to create it?

**Comment by mplatings** [comment]
@s-panferov I didn't see your pull request so I made one myself.

**Comment by jakerella** [comment]
Awesome, thanks! I made some comments over there...

**Comment by jakerella** [comment]
Never heard back on this... if we need to do anything, please reopen.
