### ISSUE TITLE
$.mockjax.mockedAjaxCalls() data key of the returned object is a string instead of an object

### ISSUE THREAD

**Issue by simonleclerc** [jakerella/jquery-mockjax#220]
Hello,

When I inspect the `data` key of the object returned by `$.mockjax.mockedAjaxCalls`, it appears to be a string `'[object Object]'` instead of the real object I was looking for.

For my need I commented this lines in the `createJsonpCallback` and I get my object back
```
// Replace the =? sequence both in the query string and the data
if ( requestSettings.data ) {
			requestSettings.data = (requestSettings.data + "").replace(CALLBACK_REGEX, "=" + jsonp + "$1");
}
```

Am I misusing `mockedAjaxCall()` ? I need to access the data to test them with CasperJS.

**Comment by jakerella** [comment]
Sorry for the delay on this... can you provide us with the `$.mockjax({ ... })` call you used to get that result?

**Comment by jakerella** [comment]
I think the issue here is that you simply convert an object (`requestSettings.data`) into a string, but that results in "[object Object]" as you noted. Instead, you may need to stringify the `data` property first:

```js
JSON.stringify((requestSettings.data)).replace(CALLBACK_REGEX, "=" + jsonp + "$1")
```

Closing for now due to inactivity.
