### ISSUE TITLE
Mocking unmatched requests

### ISSUE THREAD

**Issue by 4imble** [jakerella/jquery-mockjax#221]
Sometimes i only really care about mocking one request, however my runner (Karma) is throwing a 404 not found error if i dont mock everything that gets called.

I attempted to catch all routes by defining this upfront:

        $.mockjax({
            url: "*api/**",
            contentType: "application/json",
            type: "get",
            responseText: []
        });

        $.mockjax({
            url: "*api/**",
            contentType: "application/json",
            type: "post",
            responseText: []
        });

However it was then ignoring my explicit routes that i am setting up in each test.

In mockjax can I define a default mocked response that it will use if it does not find a match?

**Comment by dcneiner** [comment]
@4imble They are matched in order, so if you define your last call like this, it will match whatever hasn't matched another mock:

```js
$.mockjax( function ( settings ) {
	// Or whatever you want as your default response
	return {
		responseText: "Not mocked"
	}
} );
```

This is documented (a little) here: https://github.com/jakerella/jquery-mockjax#dynamically-generating-mock-definitions

**Comment by 4imble** [comment]
Many thanks for the information,

This implementation would be slightly problematic for me, I would have to go through each of my tests and define this when I want to handle an unmapped route.

I am trying to think of a way to set this globally. Other than changing the implementation so that newer routes are matched first I'm not sure what to try. Sorry, this is probably quite specific to my implementation.

I'll close it off, I think I have enough to at least get me in the right direction.
Thanks again.
