### ISSUE TITLE
Release 1.6.2

### ISSUE THREAD

**Issue by adius** [jakerella/jquery-mockjax#236]
How about releasing a version including fix of invalid repositories (plural) field in package.json.
It's really annoying to get the warning all the time =P

**Comment by jakerella** [comment]
Ugh... yeah... I keep meaning to do that... soon.

**Comment by jakerella** [comment]
Released.

**Comment by adius** [comment]
Nice, thanks!

**Comment by jakerella** [comment]
:+1: 

And hopefully 2.0.0-beta won't be far behind, but that has a lot of changes. :)
