### ISSUE TITLE
Not returning AJAX Response when using jQuery v2.1.1

### ISSUE THREAD

**Issue by jasondavis** [jakerella/jquery-mockjax#246]
I was stumped as my code was not returning a response from `MockAjax` to my actual `AJAX` `success()` function.

I then realized that this part of my application worked fine when using `jQuery v1.11.2` but as soon as I loaded `jQuery v2.1.1` it stopped working.

`MockAjax` had no problem intercepting my AJAX request, it just would not return the value back to the AJAX request that it intercepted!

I would love to know how to fix if anyone can help?

I created a quick mockup demo to show the problem in action here http://jsbin.com/vugeki/1/edit?js,console,output

In the `output` panel when you click `Run with JS` it runs an AJAX request in which MockAjax catches the request but does not return it back to the initial AJAX success function =(

**Comment by dcneiner** [comment]
I have good news for you @jasondavis! You are just using an old version of Mockjax. Update to the latest, and your code works!

To try it out quickly in your jsbin, just swap out the current mockjax reference with one of the URL's from https://cdnjs.com/libraries/jquery-mockjax

**Comment by jakerella** [comment]
Nice catch @dcneiner!

@jasondavis FYI, we also support Bower.io and npm dependency installs if you'd prefer to use one of those package managers. That usually helps in keeping your version updated. Closing this issue for now, but we can reopen if this does not solve your issue!
