### ISSUE TITLE
Url namespace

### ISSUE THREAD

**Issue by danpaz** [jakerella/jquery-mockjax#252]
Could we have a global setting to namespace urls to e.g `api/v1/*`? Few questions off the bat:
* Is this hard to do? (From a quick browse of the source code, probably not?)
* Should it be possible to override the global setting on a single mock?
* Would this be useful?

**Comment by jakerella** [comment]
* Shouldn't be too bad (I hear someone was already working on a PR :smirk_cat:)
* Yes
* I'm sure it would!

I'll target it for 2.1.0, let me know if you need help working on it.
