### ISSUE TITLE
Using mockjax with proxy  can be cache by the previus file?

### ISSUE THREAD

**Issue by vmariano** [jakerella/jquery-mockjax#256]
Hi. I'm using  mockjax with `jasmine` and I  saved the server responses in several proxy files.

My problem is , when i run the next test, aparently, mockjax read the last file used. Could be a bug or i'm wrong with the configuration? (code below)

```javascript
    it("Return a single response.", function(done) {

        $.mockjax({
            url:  urlPrefix + '/locations',
            proxy:  pathToFiles + 'singleResponse.json'
        });

        locations.find('eze').done(function (response) {
            expect(response.length).toEqual(1);
            expect(response).toEqual([{payload:"ok"}]);
            done();
        });
    });

    it("Return multiple responses.", function(done) {

        $.mockjax({
            url:  urlPrefix + '/locations',
            proxy:  pathToFiles + 'multiResponse.json'
        });

        locations.find('san martin').done(function (response) {
            expect(response.length).toBeGreaterThan(1);
            expect(response).toEqual([{payload:"ok"}, {payload:"ok"}]);
            done();
        });
    });
```

**Comment by jakerella** [comment]
Thanks for reporting this! I'll try to take a look soon and let you know what I find.

**Comment by vmariano** [comment]
Ok, after a little research, and read the reference in http://appendto.com/2010/07/mock-your-ajax-requests-with-mockjax-for-rapid-development/
I realize i can reset the configuration btw calls, so I fixed adding  the `$.mockjax.clean()` so in my case it ends like:

```javascript
    it("Return a single response.", function(done) {

        var id = $.mockjax({
            url:  urlPrefix + '/locations',
            proxy:  pathToFiles + 'singleResponse.json'
        });

        locations.find('eze').done(function (response) {
            expect(response.length).toEqual(1);
            expect(response).toEqual([{payload:"ok"}]);
            $.mockjax.clear(id);
            done();
        });
    });
```
Sorry for the rush bug report, I keep it open if you want to take a look after.  :+1:

**Comment by vmariano** [comment]
Maybe only you need to update the Readme.md, and thats all.

**Comment by jakerella** [comment]
I see what you did. Yes, that will not overwrite the previous mock handler, but instead, it adds a second handler. Unfortunately, the library only processes the first mock handler it finds, and thus the second one is never reached.

I think we should probably add a warning, at least, when that happens!
