### ISSUE TITLE
Mocking remote JSONP fails

### ISSUE THREAD

**Issue by mataspetrikas** [jakerella/jquery-mockjax#26]
the modified test code fails with jQuery 1.5 once 'calling' the remote server:

https://gist.github.com/1024911

    asyncTest('Response returns jsonp', function() {
    	$.mockjax({
    		url: 'http://example.com/jsonp*',
    		contentType: 'text/json',
    		proxy: 'test_jsonp.js'
    	});
    	window.abcdef123456 = function(json) {
    		ok( true, 'JSONP Callback executed');
    		deepEqual(json, { "data" : "JSONP is cool" });
    	};
	
    	$.ajax({
    		url: 'http://example.com/jsonp?callback=?',
    		jsonpCallback: 'abcdef123456',
    		dataType: 'jsonp',
    		error: noErrorCallbackExpected,
    		complete: function(xhr) {
    			equals(xhr.getResponseHeader('Content-Type'), 'text/json', 'Content type of text/json');
    			start();
    		}
    	});
    	$.mockjaxClear();
    });

**Comment by jakerella** [comment]
This issue should be resolved by #248 (the test case above was added and passes). It will be in the `2.0.0` release.
