### ISSUE TITLE
Implement exclude/include URL functionality

### ISSUE THREAD

**Issue by kottenator** [jakerella/jquery-mockjax#263]
Hi!

I run my dev project instance on `http://localhost:8000/`. I use _jquery-mockjax_ to mock AJAX calls to my dev instance.

And I use JSONP to get data from external URL `http://my.server/api/session/`. I don't want to mock it.

Everything is fine while I'm developing but then I deploy it to `http://my.server/staging/`. And now I have a problem: JSONP call to `http://my.server/api/session/` **is mocked now**.

I need some mechanism to avoid this. As I understand you match only _protocol + host_ and this check is hard-coded now.

It would be great to have control over it. For example, to have exclude/include list of URLs, each can be String or RegExp

**Comment by jakerella** [comment]
Can you show me your mocking code? I'm not sure why the request would not be mocked in one environment and mocked in the other.

**Comment by kottenator** [comment]
I'm using mockjax implicitly, with ember-cli-mirage. I can provide Mirage config

**Comment by jakerella** [comment]
I would need to see the mockjax config (that is, what you're trying to match) in order to have an idea of what's going on. Really, what I need is a reproducible bug that I can diagnose, but I'll see what I can do with just the config.

**Comment by kottenator** [comment]
Sure, I'll try to help you

**Comment by kottenator** [comment]
Hi! I was trying to figure out what causes the problem. And I do apologize, it's nothing about your lib.
I use `ember-cli-mirage` which appears to be using `Pretender`, not `jquery-mockjax`. 
Sorry, I'm resolving this bug.

**Comment by jakerella** [comment]
Ha! Okay then. No worries.
