### ISSUE TITLE
Conflict with raven.js

### ISSUE THREAD

**Issue by begedin** [jakerella/jquery-mockjax#267]
I've discovered this issue while using [raven.js](https://github.com/getsentry/raven-js/) in conjunction with [ember-data-factory-guy](https://github.com/danielspaniel/ember-data-factory-guy) within the same ember-CLI app. ember-data-factory-guy relies on [jquery-mockjax](https://github.com/jakerella/jquery-mockjax) as a dependency.
 
There is a potential workaround in that specific case due to a probable bug in `ember-data-factory-guy`, but the conflict still exists when `raven.js` and `jquery-mockjax` are being used at the same time.

In our case, it looks like the mockjax ajax wrapper is applied before the raven.js wrapper. The result of that is that when an ajax request s being executed, the outer, raven.js wrapper runs first and then calls the mockjax wrapper.

From https://github.com/getsentry/raven-js/blob/master/plugins/jquery.js#L51

```JavaScript
var _oldAjax = $.ajax;
$.ajax = function ravenAjaxWrapper(url, options) {
    // unimportant parts cut out

    // Taken from https://github.com/jquery/jquery/blob/eee2eaf1d7a189d99106423a4206c224ebd5b848/src/ajax.js#L311-L318
    // If url is an object, simulate pre-1.5 signature
    if (typeof url === 'object') {
        options = url;
        url = undefined;
    }

    // Force options to be an object
    options = options || {};

    try {
        var jqXHR = _oldAjax.call(this, url, options);
        // ...
    }
};
```

From https://github.com/jakerella/jquery-mockjax/blob/master/src/jquery.mockjax.js#L525:

```JavaScript
// The core $.ajax replacement.
function handleAjax( url, origSettings ) {

	// If url is an object, simulate pre-1.5 signature
	if ( typeof url === 'object' ) {
		origSettings = url;
		url = undefined;
	} else {
		// work around to support 1.5 signature
		origSettings = origSettings || {};
		origSettings.url = url;
	}
        
        // ...
}
```

The process which breaks the ajax request is as follows:

1. Commonly, an Ember app will call ajax using `Ember.$.ajax(hash);` There is a `hash,url`.
2. Raven ajax wrapper will figure out what the arguments are, then pass on the ajax call with 

```
 _oldAjax(undefined, options)
```

At this point, `options.url` is still untouched

Since mockjax already prewrapped the default ajax method, what actually ends up being called is `handleAjax(url, origSettings)`

`url` is undefined, while `origSettings` is is the options object from the previous call. 

For some reason, mockjax now overwrites the url with undefined. I believe it should check if `origSettings.url` has a value first, before overwriting it, but I'm not sure if I'm missing some specification.

In any case, since mockjax is the one that's blanking out the request URL, I'm creating this issue here first. If, however, it's determined that the issue is with how raven.js does it, I will create an issue there as well.

**Comment by jakerella** [comment]
Thanks for the report! The real issue here is that our library is going off of an old spec for the jQuery `ajax()` method which requires a URL in the first argument slot. We should be able to update that to match the current spec which also accepts a `url` property of a single (object) argument to the method.
