### ISSUE TITLE
Support expectations and verification

### ISSUE THREAD

**Issue by travi** [jakerella/jquery-mockjax#27]
Today, mockjax is more of a stub than a mock. It would be a great improvement (at least in testing) if you could also set expectations on the mock within a test and then verify that the expectations were fulfilled. This allows testing of the behavior (calling the proper service, passing the proper values) rather than just testing the resulting state assuming that the stub is set up to return the proper data needed for the particular test.

**Comment by jakerella** [comment]
Closing for now due to inactivity and lack of interest. While I'm not opposed to the idea, it's just not something I think the library _needs_. If someone wants to take a stab at an implementation I'll review.
