### ISSUE TITLE
migrate jQuery 2.2

### ISSUE THREAD

**Issue by klammbueddel** [jakerella/jquery-mockjax#281]
http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

Since the 8th of  January jQuery 2.2. is out. It would be nice if the bower.json could be updated to work with v2.2. It currently sticks to 2.1 which raises a conflict in bower when using jQuery 2.2.

Maybe this is fixed by just changing the bower.json?

**Comment by klammbueddel** [comment]
One update on this.. obviously some more work needs to be done than just changing the dependency. Most of our tests fail if we just switch over to jQuery 2.2. I currently have no time to dig deeper into this, but it would be nice if this would work in the near future ;)

**Comment by jakerella** [comment]
You can use Mockjax with jQuery 2.2.x, all tests pass and things work fine with it in all of my testing across 4 different browsers on 3 operating systems. I see that the bower file does say that the dependency is on jQuery 2.1.3, and I have updated it to reflect the true dependency (`>=1.5.0`). This will be in the next release, which may be a while, but you can use the `master` branch if you need to.
