### ISSUE TITLE
Unmocked ajax calls array causes memory leak

### ISSUE THREAD

**Issue by suchipi** [jakerella/jquery-mockjax#282]
The unmockedAjaxCalls array never gets cleared, so every xhr object cannot be garbage collected. As such, if an application has this library loaded, and many requests with large responses are made (anywhere in the app), memory can get used up very quickly.

There is (probably) value to retaining unmocked ajax calls, but it'd be great if there was a setting available that could tell mockjax to not hold onto past ajax calls.

**Comment by jakerella** [comment]
Absolutely. This is a simple addition, I'll try to get it into the next minor release. It will probably just be a new method which _only_ clears that array. Note that the `clear()` method _does_ currently clear the unmocked calls, but of course it also clears any mock handlers already set up.

**Comment by suchipi** [comment]
I'm not too privy to having to call the method constantly- if I never use the calls, I'd rather not use up the memory in the first place. It doesn't seem like the contents of the array are ever used internally; could something like `$.mockjaxSettings.retainObjectCalls` be added that defaults to `false`? Or is there a functional reason a reference is held to each response that isn't apparent at first glance?

Clearing the calls by manually calling a method isn't a very big deal in testing, but we also use this library in our application to stub network responses from localStorage when the device is offline. It'd be undesirable to have to clear the calls in our application code just to work around the library's default behavior.

**Comment by jakerella** [comment]
Adding an option to retain unmocked calls is also a very reasonable suggestion. I think we can do that in the same update.

That said, **this library is not intended for production use**. It is intended for testing. As such, many things have not been accounted for that would be in a library intended for use in production. I do not recommend using this as a stub for a caching mechanism as you suggest. We simply aren't writing the library for that use case and as such there are lots of potential issues, as you have already discovered.

**Comment by suchipi** [comment]
I created a PR implementing these changes. Feedback would be appreciated

**Comment by jakerella** [comment]
I very much appreciate the effort! I have a few comments on the PR, but generally it looks fine (need to look closer later).

**Comment by suchipi** [comment]
I appreciate the library :smiley: 
I added some commits to the PR branch to address your comments; let me know if you see anything else that should be changed.

**Comment by jakerella** [comment]
PR merged into `master`, closing this one.
