### ISSUE TITLE
Mockjax Webpack Integration

### ISSUE THREAD

**Issue by kamrenz** [jakerella/jquery-mockjax#285]
When utilizing jquery-mockjax with Webpack I keep getting a $.mockjax is undefined. Do you have an example repo with jquery-mockjax integration working?

**Comment by kamrenz** [comment]
Here is where the issue lies... When I utilize jquery-mockjax within Webpack as an AMD module, jquery-mockjax thinks it is running inside of a CommonJS module. When looking at the Mockjax code below it should enter the first if block, however it goes into the second if block.

```
	// AMDJS module definition
	if ( typeof define === 'function' && define.amd && define.amd.jQuery ) {
		define(['jquery'], function($) {
			return factory($, root);
		});

	// CommonJS module definition
	} else if ( typeof exports === 'object') {

		// NOTE: To use Mockjax as a Node module you MUST provide the factory with
		// a valid version of jQuery and a window object (the global scope):
		// var mockjax = require('jquery.mockjax')(jQuery, window);

		//Changing the code to AMD-style syntax here makes Mockjax work??
		// module.exports = factory;
		define(['jquery'], function($) {
			return factory($, root);
		});

	// Global jQuery in web browsers
	} else {
		return factory(root.jQuery || root.$, root);
	}
```

**Comment by jcreamer898** [comment]
You may be able to utilize the `imports-loader` to do something like this...

```js
      {
        test: /jquery.mockjax$/,
        loader: "imports?define=>false",
      }
```

I haven't tested this theory for mockjax, but have done it for some other libs that use UMD.

**Comment by jakerella** [comment]
PR #284 just landed in `master` and may solve your problem. I believe @bt was using Mockjax with webpack and ES6 module loading. See if that works for you (but note that that PR is not in an official release yet, just on the `master` branch).

**Comment by kamrenz** [comment]
The answer is in https://github.com/jakerella/jquery-mockjax/pull/284

**Comment by jakerella** [comment]
Glad to hear you figured it out!

**Comment by ponnuru** [comment]
we need to use this require('jquery-mockjax')($, window);  inside define module in test

**Comment by laveesht** [comment]
i know this is closed, but for some looking for how to `fix Common Js require issue`,
we worked around in `webpack` by forcing it to load as browser mode,
```
{
        test: require.resolve('jquery-mockjax/dist/jquery.mockjax.js'),
        use: ['imports-loader?this=>window,exports=>""']
}
```
