### ISSUE TITLE
file:// problems on Phonegap

### ISSUE THREAD

**Issue by vincentracine** [jakerella/jquery-mockjax#286]
Im trying to use Mockjax on my IOS with Phonegap and because the url starts with file:// nothing happens. Am I doing something wrong?

mock.js

```
$.mockjax({
    url: "api/authenticate",
    method: 'POST',
    response: function (request) {...}
});
```

login.js

```
$.post('api/authenticate', { 
             email: email, 
             password: password 
         }, null, 'json')
    .done(function(response){...})
    .fail(function(xhr){...});
```

**Comment by jakerella** [comment]
Usually a `file:///...` url is a bit difficult to work with using Ajax. I'm not sure how Mockjax would perform in this case. Would you not be able to use a tool like `http-server` (node module) to run a local server for testing?

**Comment by jakerella** [comment]
I'm going to close this one for inactivity. It's an interesting use case, but `file:///` URLs are notoriously bad with Ajax, and probably something we won't support.
