### ISSUE TITLE
Simplify code by using ajaxTransport

### ISSUE THREAD

**Issue by Zyphrax** [jakerella/jquery-mockjax#288]
Won't you be able to greatly simplify the code by intercepting ajax calls by registering an ajaxTransport? http://api.jquery.com/jQuery.ajaxTransport/

I'm currently working on a mechanism that will intercept ajax calls in a WebView on iOS and that led me to this framework.

For example:

``` javascript
$(function() {
  $.ajaxTransport("+*", function(options, originalOptions, jqXHR) {
    return {
      send: function(headers, completeCallback) {
         completeCallback(200, "success");
      },
      abort: function() {
         completeCallback(418, "I'm a teapot");
      }
    };
  });
});
```

**Comment by jakerella** [comment]
Thanks for reaching out! That's a good question, and the easy (and incomplete) answer is that when Mockjax was created `ajaxTransport` did not exist (it was added in v1.5). However, if you look at how we do things, we call the underlying jQuery `ajax` method, but we create our own custom XHR object. You can read about the xhr option of the `ajax` method on the [API docs](http://api.jquery.com/jQuery.ajax/) and see where we [use it in the code](https://github.com/jakerella/jquery-mockjax/blob/master/src/jquery.mockjax.js#L675).

I've looked at `ajaxTransport` and while it is a cool option, it would require a major overhaul to use. I'm not against it, but that isn't really in the roadmap. The `xhr` option provides us everything we need in terms of mocking functionality currently. I'm open to looking at a complete refactor, but that's basically a new library! It would require a completely new set of tests as well.

I'll leave this issue open for any other comments, but for now, it's not in the plan. That said, again, thanks for your question!

**Comment by Zyphrax** [comment]
Sure, not a problem! Great work on the framework, looking at the code I can see that a lot of thought and care has gone into it (more open-source projects should be like this).

**Comment by jakerella** [comment]
Closing for now... this might be something to look at for a (possible) `v3` overhaul one day.
