### ISSUE TITLE
Ability to return dynamic HTTP response headers

### ISSUE THREAD

**Issue by marvinpinto** [jakerella/jquery-mockjax#296]
Hey folks,

I am wondering if it is possible to somehow return dynamic header values in mockjax responses.

I have tried something similar to the following:

``` javascript
var dynamicHeader = function() {
  returnValue = {'X-Dynamic-Header': Math.random()}
  console.log("header is " + JSON.stringify(returnValue));
  return returnValue;
}

$.mockjax({
  status: 200,
  type: 'GET',
  url: '/api/test',
  dataType: 'json',
  headers: dynamicHeader(),
  responseText: {}
});
```

What I have observed is that the `dynamicHeader` function only executes the very first time which results in the `X-Dynamic-Header` value staying the same.

The ability to respond with dynamic headers is very useful in testing situations where the logic needs to adjust according to what an API responds with. `X-Poll-Interval` is a good example here.

This very likely might be the result of me not being that familiar with Javascript, so any pointers would be much appreciated.

**Comment by jakerella** [comment]
Yep, it's possible. But you'll need to use a custom `response` function, not the basic setup you have above. For example:

```js
$.mockjax({
  status: 200,
  type: 'GET',
  url: '/api/test',
  dataType: 'json',
  response: function(settings) {
    this.responseText = JSON.stringify({});
    this.headers = dynamicHeader();
  }
});
```

Read more about it here: https://github.com/jakerella/jquery-mockjax#callback

**Comment by marvinpinto** [comment]
This is perfect! Thank you very much @jakerella!

(`this.headers` is the bit I was missing!)

I'm going to close this issue now since there is nothing that needs doing here.
