### ISSUE TITLE
Can Data Match Regex?

### ISSUE THREAD

**Issue by loganrenz** [jakerella/jquery-mockjax#300]
I have a PUT request that contains JSON that is will change from one run to the next. I would like to match on just part of the data of the request. If I could do something like: 

`.*"core": "Place".* `

That would be great, but it doesn't look like that's possible.

The other solution I tried was passing a function as the data:

`
$.mockjax({
'url' : '/api/v1/placesearch',
'method' : 'POST',
'data' : function( data ) {return $.parseJSON(data).core == "Place"},
'responseTime' : 10,
'status' : 200
});
`

But I couldn't get that to match either.

**Comment by jakerella** [comment]
Hmm... you're right to use the `function` version of the `data` option, I'm not sure why this isn't matching other than perhaps the `data` argument is already an object? Can you post the actual `$.ajax()` request you're trying to mock? Generally speaking this looks correct.

**Comment by loganrenz** [comment]
If I set a debug point at var identical = true of jQuery.mockjax.js

`function isMockDataEqual( mock, live ) {
		var identical = true;
...
}`

mock is a function: anonymous/</<.data(json)
live (is a typeof string) has the value:

`"{"query":"Starbucks","core":"VendorPlace","restriction":"global","ne":{"y":37.344573211931895,"x":-121.97527885437012},"sw":{"y":37.319048778895926,"x":-122.08514213562012},"page":1,"pageSize":100,"advancedQuery":{}}"`

As I walk through, it returns mock === live. Which is false.


I tried removing the $.parseJSON and just saying `return data.core` but that didn't get me what I needed either.

Did I supply what you were asking for?

**Comment by loganrenz** [comment]
Oh, I see that VendorPlace and Place aren't the same, but that's not it in this case. I have tried both ways.

**Comment by loganrenz** [comment]
Another piece of information: I am running version 2.1.1

And also

In Firefox, stopped at debug point on line 208:

`if ( !requestSettings.data || !isMockDataEqual(handler.data, requestSettings.data) )`

If I run this on the console, the result is true: `handler.data(requestSettings.data)`

Where I understand handler.data to be the function `function( data ) {return $.parseJSON(data).core == "VendorPlace"}`

**Comment by jakerella** [comment]
Aaah... using `data` as a function is new in `v2.2.0`! I think you'll need to upgrade to use that, unfortunately.

**Comment by loganrenz** [comment]
Ah ha! 

Yes I see it now in the code: `if ( $.isFunction(mock) ) {return !!mock(live);}`

I thought I was missing something. 

Thank you!

**Comment by jakerella** [comment]
No worries! Glad you got it fixed up.
