### ISSUE TITLE
Mockjax doesn't work in Ember 2.10

### ISSUE THREAD

**Issue by ronaldsuwandi** [jakerella/jquery-mockjax#308]
Somehow mockjax no longer mock my AJAX requests for my tests when I upgraded Ember.js from 2.3.0 -> 2.10.0. I figured it doesn't works because my service is using `Ember.$.ajax()` instead of directly `$.ajax()`

My assumption is somewhere between Ember 2.5 - 2.10 `Ember.$` no longer points to the global jQuery instance (can't confirm which version yet as I'm in the middle of upgrading 2.3->2.4)

Reference: http://stackoverflow.com/questions/41255855/ember-js-cant-mock-ajax-using-jquery-mockjax?noredirect=1#comment69832893_41255855

**Comment by jakerella** [comment]
I've added a simple Ember app in the `/test/` directory with one model and one unit test file. In [this test file](https://github.com/jakerella/jquery-mockjax/blob/ca691aa14a6252ae217ddd94d0e86aee3106d3fc/test/ember/mockjax-app/tests/unit/models/person-test.js) I use Mockjax both off of the `Ember` namespace and also globally (`window.$`) and both run fine and do, indeed, mock the model REST API requests.

My recommendation is to ensure you have the latest version of Mockjax, but this is running with Ember 2.10.0. I'm not sure what else might be going on, but I'd need a lot more information about the application and how the tests are set up to figure things out.

**Comment by ronaldsuwandi** [comment]
That's weird, thanks for testing it out, most likely the bug is on our side. I'll close the ticket for now and if this happens again when I upgrade to 2.10 I'll grab more details and let you know

**Comment by ronaldsuwandi** [comment]
@jakerella I tried to upgrade from 2.9->2.10 and it failed again and I finally figured out the reason why mockjax didn't work. I actually have additional jQuery dependency in my bower file and on `ember-cli-build` I actually imported jQuery. In Ember 2.10, reimporting jQuery somehow overrides the global instance, hence `Ember.$ !== $` while in the previous versions it worked fine.

**Comment by jakerella** [comment]
Glad to hear you have it figured out! Perhaps if you were able to pull in Mockjax after that separate import then it might work. Mockjax binds to whatever the global jQuery instance is (not directly to `Ember.$`)

**Comment by ronaldsuwandi** [comment]
It actually works now, what I did is to remove imprting jQuery in my `ember-cli-build` and mockjax is working fine :-)

**Comment by jakerella** [comment]
Sweet, glad to hear it!
