### ISSUE TITLE
Use mockjax in ES6 module style?

### ISSUE THREAD

**Issue by craigcosmo** [jakerella/jquery-mockjax#316]
I have code like this

**method.js**
```
export function deleteImageFromServer(id){
    return $.post('http://localhost:8000/' + 'delete' , { id: id}, function(r){
        return r
    })
}
```

**home.spect.js**
```
import {deleteImageFromServer} from './method'
import expect from 'chai'

    describe('deleteImageFromServer', function () {
        it('should delete image', function () {

            deleteImageFromServer(1).then( (r) =>{
                expect(r).to.equal('good')
            })
        })
    })
```

Do you have suggestion how to use mockajax in this case? I want to mock the jquery request and return `good` if the request is success.

**Comment by jakerella** [comment]
Mockjax does not currently support the new ES6 `import`/`export` module system, so this would be a new feature. Definitely something we would like to do, but for now you should be able to use the global `$.mockjax()` function in your tests. Check the README file in the project for how to create mocks.

**Comment by tim-we** [comment]
Maybe the question was more about how to get it to work at all, not importing any methods directly. I got it working using Vitest:
```js
import $ from "jquery";
import mockjaxFactory from "jquery-mockjax";

window.jQuery = window.$ = $;
mockjaxFactory(window.$, window);
```
