### ISSUE TITLE
some requests can not be captured

### ISSUE THREAD

**Issue by ylzsmallsun** [jakerella/jquery-mockjax#317]
I mocked 4 requests, two succeed and the other two could not be captured.
two failed requests are like below:

http://localhost:8888/odata/v2/restricted/a/a$format=json&%24filter=code%20eq%20%27Boss%27&%24orderby=f%20desc

http://localhost:8888/odata/v2/restricted/a,b,c,d,e,f/f?$format=json&k=datetime%272017-05-11T00%3A00%3A00%27&m=false&code=Boss

so why?

**Comment by jakerella** [comment]
Thanks for sending in a report! I'll need to see a lot more information to be able to help you though. For starters, I would need to see the mockjax code where you set up these request captures.

**Comment by ylzsmallsun** [comment]
Hi jakerella,
 
I have found the root cause. The " ' " contained in the url won't be encoded to "%27". 
But I saw an error output(MOCK GET:) in console: "$format=json&NaNilter" . It should be "$format=json&%24filter".

**Comment by jakerella** [comment]
Interesting! I'll see if I can find a solution there, but the easy thing is for you to call `encodeURI()` before passing the URL into Mockjax.

**Comment by ylzsmallsun** [comment]
I always call the encodeURIComponent() for the url parameters. At the beginning, I copied the url from network. Then, I met the above issue. The cause is there is a difference between the request url from network and the url in the code snippet. For example:
encodeURIComponent("$filter") + '=' + encodeURIComponent("Code eq 'boss'")
"%24filter=Code%20eq%20'boss'"

But the corresponding substring in the network tab is "%24filter=Code%20eq%20%27boss%27".
So this is what I mean above 'The " ' " contained in the url won't be encoded to "%27".' And I correct the url value  in the mockjax with the value in the code rather than coping it from network tab. Finally all mock requests can work well.

**Comment by jakerella** [comment]
Ah... strange, I didn't know that the apostrophe ( ' ) was not encoded! I'll see if we can get a fix in here.

**Comment by jakerella** [comment]
I've taken a closer look at this issue, and I see what's happening. However, we do _not_ encode the URI when doing the URL matching for mock handlers. I understand that the browser is doing something outside of `encodeURIComponent()` and as such, we would have to start adding a lot of custom logic for this. The thing is that the mock handler URL is not actually a URL... for example, you can use wildcard characters (`*`) to match variable URL parameters.

For now, I don't see anything we can or should do in the library. However, you should be able to handle this issue by using the actual encoded URL in your mock handler. Below is an example, note that the single quote is _not encoded_, which is the behavior seen in `encodeURIComponent()`.

```
$.mockjax({
    url: "/api/foo?format=json&%24filter=Code%20eq%20'boss'",
    contentType: 'application/json',
    responseText: { foo: 'bar' }
});

// And then your Ajax call could be...
$.ajax({
    url: "/api/foo?format=json&" + encodeURIComponent("$filter") + '=' + encodeURIComponent("Code eq 'boss'"),
    dataType: 'json',
    // ...
});
```
