### ISSUE TITLE
add $.mockjax.handlers() method

### ISSUE THREAD

**Issue by hixus** [jakerella/jquery-mockjax#321]
There seems no way to get all mocked handlers. I would like to override single request but in the test level I don't know the indexes of mocked handlers as there are couple helpers that add additional handlers to mockjax.

**Comment by jakerella** [comment]
You're right, there is not an easy way to get all current handlers. But my question would be what are you trying to retrieve them for? You say "override single request", but I'm not sure what that means. I might be able to help you solve that problem without a new feature. Note that there is another issue ( #184 ) to add unique IDs to each handler, which could then allow for querying of handlers and other such things. That has not been done yet.

**Comment by jakerella** [comment]
Resolved by #327
