### ISSUE TITLE
Demo doesn't seem to work?

### ISSUE THREAD

**Issue by oshihirii** [jakerella/jquery-mockjax#322]
I am trying to get the demo code in the readme working ([codepen](https://codepen.io/oshihirii/pen/MvxVvr)) and am getting the error:

> Cannot read property 'status' of undefined

**HTML**
```html
  <button class="clicker">clicker</button>
  <div id="fortune"></div>
```

**JS**
```js
$.mockjax({
  url: "/restful/fortune",
  responseText: {
    status: "success",
    fortune: "Are you a mock turtle?"
  }
});

$(document).on("click", ".clicker", function() {
  $.getJSON("/restful/fortune", function(response) {
    if (response.status == "success") {
      $("#fortune").html("Your fortune is: " + response.fortune);
    } else {
      $("#fortune").html("Things do not look good, no fortune was told");
    }
  });
});
```

**Comment by oshihirii** [comment]
Hmm, works with jQuery 1.9.1 but not jQuery 3.2.1.

**Comment by jakerella** [comment]
Yep, some things broke in jQuery 3 (or maybe 2?) that requires the latest mockjax (or at least newer than 1.x). Is your issue resolved then?

**Comment by jakerella** [comment]
Closing for non-response... let me know if you're still having trouble.
