### ISSUE TITLE
Handlers are not getting cleared when defining multiple requests

### ISSUE THREAD

**Issue by dshrestha** [jakerella/jquery-mockjax#324]
I am unable to clear the handler for multiple requests(https://github.com/jakerella/jquery-mockjax#defining-multiple-requests)
I tried the example provided in the doc as well as tried to loop through the index array and clear them up individually but it didn't work for me. 

mockjax ver 2.2.0, 
jquery ver 1.11.3

```
    let mockConceptLockdownMetrics = function() {    
        return $.mockjax([{
            url: /\/platformservices\/accelerator\/conceptLockdownMetrics\/([\d]+)$/i,
            responseTime: 0,
            urlParams: ["id"],
            contentType: "application/json",
            response: function(settings) {
                this.responseText = "some data";
            }
        }, {
            url: /\/platformservices\/accelerator\/conceptLockdownMetrics$/i,
            responseTime: 0,
            contentType: "application/json",
            response: function(settings) {    
                this.responseText = "some data";
            }
        }]);
    };
    let handlers = mockConceptLockdownMetrics();
    $.mockjax.clear(handlers[0]);//eg : [1,2]
    $.mockjax.handler(1);//returns object

```

**Comment by jakerella** [comment]
Hi! Thanks for the report. I'll try to look at this soon, but my schedule is a little crazy right now. Pull requests are welcome!

**Comment by dshrestha** [comment]
@jakerella my apologies, it must have been my browser caching or something but I am unable to reproduce this error. Sorry for the false alarm.
