### ISSUE TITLE
only work with jquery2.1.0, not 2.20 and upper, with example

### ISSUE THREAD

**Issue by dstang2000** [jakerella/jquery-mockjax#348]
thank you, jakerella for your response. 
Here, an example:

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>mockjax test</title>
</head>
<body>

	<div class="info"> waiting ... </div>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mockjax/1.6.2/jquery.mockjax.js"></script>

	<script>

$(function(){
	var mocked = true; 
	if(mocked){
		$.mockjax({
			url: "http://g.cc/restful/api",
			contentType: "application/json",
			responseText: {
				news: "hello World!",
				date: "5-24"
			}
		});
	}	

	$.get("http://g.cc/restful/api",  function(data){
		console.log(data)
		$(".info").html(data.news + "," + data.date);
	});	

});
</script>

</body>
</html>

**Comment by jakerella** [comment]
Can you please post what error you are receiving, or what is happening? Things all work in our tests, so I'm not sure what's going on with your example.

**Comment by dstang2000** [comment]
when I open the html page in a browser( chrome).

if I use jquery1.11.1, all is ok.
but if I use jquery3.4.1,  
F12, the browser console says:  in function(data), the data is undefined.

**Comment by jakerella** [comment]
Sorry, but this is working. I wrote the following test in `/test/test-bugs.js` and ran the tests from the command line using jQuery 2.2.4 and 3.4.1 (`$ grunt test:version:3.4.1:bugs`) and all tests pass. I'm not sure why this isn't working for you, but without further information I am unable to replicate this issue, and therefore can't really help you.

I'm going to close this issue, you can still comment on it, please don't open a new issue, just comment here and provide any updated information you might have and we can re-open it.

The test I added:
```
t('Bug #348: getting undefined data', function(assert) {
	var done = assert.async();
	
	var mocked = true;
	if (mocked) {
		$.mockjax({
			url: "http://g.cc/restful/api",
			contentType: "application/json",
			responseText: {
				news: "hello World!",
				date: "5-24"
			}
		});
	}
	$.get("http://g.cc/restful/api",  function(data){
		assert.equal(data.news, "hello World!");
		done();
	});
});
```

Test command and output:
```
$ grunt test:version:3.4.1:bugs
Running "test:version:3.4.1:bugs" (test) task
[ 'http://localhost:4000/test/index.html?jquery=3.4.1&testFiles=["bugs"]&ignoreFiles=null' ]
LOADING http://localhost:4000/test/index.html?jquery=3.4.1&testFiles=["bugs"]&ignoreFiles=null

Running with params: {"jquery":"3.4.1","testFiles":"[\"bugs\"]","ignoreFiles":"null"}
Running Module: Miscellaneous Bug Tests .................

Time: 3031ms, Total: 34, Passed: 34, Failed: 0

Done.
```
