### ISSUE TITLE
Add $.mockjax.clear('/someurl') 'clear by url' to README documentation

### ISSUE THREAD

**Issue by jedateach** [jakerella/jquery-mockjax#349]
The README doesn't indicate you can use `$.mockjax.clear("/some-url")`. I found this out by accident.

https://github.com/jakerella/jquery-mockjax/blob/fe5c125e68ecdabd3eb378662dff53e5dda33ba5/src/jquery.mockjax.js#L948

**Comment by jakerella** [comment]
Done!
