### ISSUE TITLE
Setting namespace works only if url is a string (doesn't work for RegExp)

### ISSUE THREAD

**Issue by gregid** [jakerella/jquery-mockjax#354]
When url is RegEx pattern and not a string the `namespace` is being ignored.
This will work:
```js
$.mockjax({
    url: "/rest"
})
```
The following will fail to recognize namespace:
```js
$.mockjax({
    url: /^\/api\/auth$/
})
```

As a workaround I created a helper function:
```js
    const nsUri = function (pattern, namespace) {
        const namespaceToUse = namespace || $.mockjaxSettings.namespace;
        const newPattern = namespaceToUse && pattern && pattern.source
            ? pattern.source.replace('^', `^(${namespaceToUse})?`)
            : pattern;

        return new RegExp(newPattern);
    };
```
This way the following will work as expected:
```js
$.mockjax({
    url: nsUri(/^\/api\/auth$/)
})
```
related to: #253

**Comment by jakerella** [comment]
Hey there! sorry for the delay. Yep, this would only work with string url matchers.

Happy to accept a PR to support this! Not sure I'll be able to get to it soon though.

**Comment by gregid** [comment]
@jakerella PR submitted - review whenever you have time.
