### ISSUE TITLE
Compatibility with jQuery 3.x

### ISSUE THREAD

**Issue by pistolero38** [jakerella/jquery-mockjax#355]
Seems that there is an issue when using jQuery 3.x (I'm using the last one at this time : 3.5.1).

No data are in the response of the ajax call. It seems that the issue is in function `_xhrSend`:
```
// jQuery 2.0 renamed onreadystatechange to onload
onReady = this.onreadystatechange || this.onload;
```
With jQuery V3.x, when calling  `this.onreadystatechange` it will call finally `callback `method with type == 'error'. In my case the reponse is OK (200) but no data are returned.

I changed the code in mockjax :
```
onReady = this.onload;
```
But maybe it woul be better to have
```
onReady = this.onload || this.onreadystatechange;
```
for compatibility

**Comment by pistolero38** [comment]
the call is made as :

```
$.ajax({
      url: config.serverUrl + config.loginPath,
      type: 'POST',
      data: JSON.stringify(sentData),
      contentType : 'application/json',
      dataType : 'json'
})
```

**Comment by jakerella** [comment]
Hi! Sorry for the delay. I've added jQuery 3.5.1 to our test suite, and all tests run as expected. I definitely get data back in mocks. The call you have there looks like, but I would recommend creating a minimal test in your environment. I'd also need to see the mock you created.

**Comment by pistolero38** [comment]
Hi !
Thank you for your answer. I use version 1.5.3 of mockjax. I will upgrade to last version and see if the issue still occurs.

The mock created :

$.mockjax({
                url: serverUrl + 'authenticate/login',
                responseText: JSON.stringify({
                    "status": "OK",
                    "sessionId": "12345"
                }),
                responseTime: 300,
                status: 200
            });

serverUrl is a parameter.

**Comment by pistolero38** [comment]
I was using V1.5.3 of mockjax.
But with the upgrade to version 2.5.1 it works well.

Sorry for the inconvient, this topic can be close now.
Thanks for your support !
