### ISSUE TITLE
jQuery 4.0.0-beta.2 compatibility

### ISSUE THREAD

**Issue by jayaddison** [jakerella/jquery-mockjax#362]
## Problem Description

The second beta release in preparation for jQuery 4.0.0 was [released](https://blog.jquery.com/2024/07/17/second-beta-of-jquery-4-0-0/) recently; the 4.x.x branch contains some breaking changes that affect `jquery-mockjax` - notably the removal of `$.isArray`, `$.isFunction` and `$.parseJSON`.

## Possible Solutions

  * `Array.isArray` should be a drop-in replacement for `$.isArray`.
  * `typeof x === 'function'` can [apparently _usually_ replace](https://api.jquery.com/jQuery.isFunction/) `$.isFunction`.
  * `JSON.parse` should be available as a replacement for `$.parseJSON`.

I'll plan to prepare a pull request that offers these changes.

## Additional Context

Discovered during preparation of select2/select2#6332.

**Comment by jakerella** [comment]
Thanks for the tip! I'll need to think about how to implement this, but looks like a good thing to work on.

**Comment by jayaddison** [comment]
You're welcome!  [These JSONP/script-related tests](https://github.com/jakerella/jquery-mockjax/blob/4ca7ace3daf8cfb54134555ee91c4b1cff671065/test/test-bugs.js#L290-L330) may be relevant; jQuery 4.x seems to be stricter about some evaluation of remote JavaScript.

**Comment by jayaddison** [comment]
@jakerella I've opened #363 with some work-in-progress attempting to achieve the upgrade.  The JSONP tests are yet-unresolved there.

**Comment by jayaddison** [comment]
Resolved by #363 - I'll monitor for any related bugreports until and (assuming all goes well!) for some time after the 2.7.0 release.
