### ISSUE TITLE
Mockjax is cloning the whole settings.context

### ISSUE THREAD

**Issue by csharbel** [jakerella/jquery-mockjax#74]
Hi

Mockjax is cloning the whole settings.context when it is using $.extend. There are two issues here -

1) It clones the whole object structure (Maybe a whole DOM tree).

2) We need to have some references to update after getting the response (like updating knoclout observables or UI based on the response). In this case we are not able to identify the object back as we are getting a new object structure.

JQuery also had similar issues that was fixed. See here http://bugs.jquery.com/ticket/9887.

#

We will need to stop making deep copies if it specified in  jQuery.ajaxSettings.flatOptions. Below is the fn added by jquery to fix this. 

==================================================================
	// A special extend for ajax options
	// that takes "flat" options (not to be deep extended)
	// Fixes #9887
	function ajaxExtend(target, src) {
		var key, deep,
		flatOptions = jQuery.ajaxSettings.flatOptions || {};
		for (key in src) {
			if (src[key] !== undefined) {
				(flatOptions[key] ? target : (deep || (deep = {})))[key] = src[key];
			}
		}
		if (deep) {
			jQuery.extend(true, target, deep);
		}
		return target;
	}

================================================================
We need to the same logic and call it at the two places where we do $.extend. Can also send in the changes. Or should I fork and commit?

**Comment by jakerella** [comment]
This issue was resolved by #247 and will be in v2.0.0
